"""
{{Skill Name}} — Hermes plugin package template (generated by Skill Factory)

This template produces a plugin PACKAGE: a directory containing plugin.yaml and
__init__.py. Do not install it as a loose .py file — Hermes plugin discovery
skips non-directories (hermes_cli/plugins_discovery.py::scan_directory), so a
loose .py never loads.

Layout produced:
    ~/.hermes/plugins/{{skill-name}}/plugin.yaml
    ~/.hermes/plugins/{{skill-name}}/__init__.py

Install:
    mkdir -p ~/.hermes/plugins/{{skill-name}}
    cp plugin.yaml  ~/.hermes/plugins/{{skill-name}}/
    cp __init__.py  ~/.hermes/plugins/{{skill-name}}/
    hermes plugins enable {{skill-name}} --no-allow-tool-override

Usage:
    /{{skill-name}}          (Hermes plugin commands are flat and hyphenated)
"""

from __future__ import annotations

import json

PLUGIN_NAME = "{{skill-name}}"
PLUGIN_VERSION = "1.0.0"
PLUGIN_DESCRIPTION = "{{description}}"

_CTX = None


def _run(args=None, **kwargs):
    """Command/tool handler.

    Handlers are called as handler(args, **kwargs) — ctx is NOT threaded
    through, so it is captured at registration instead. Always return a string
    and never let an exception escape.
    """
    try:
        # Step 1: {{step description}}
        # Step 2: {{step description}}
        # Step N: {{step description}}
        return (
            "Running **{{Skill Name}}** workflow.\n"
            "Edit `~/.hermes/plugins/{{skill-name}}/__init__.py` to implement the steps."
        )
    except Exception as exc:
        return json.dumps({"error": f"{type(exc).__name__}: {exc}"})


def register(ctx) -> None:
    """Register this plugin with the Hermes agent."""
    global _CTX
    _CTX = ctx

    ctx.register_command(
        "{{skill-name}}",
        _run,
        description="{{description}}",
    )

    # Optional: expose the workflow as a model-callable tool.
    #
    # def _tool(args=None, **kwargs):
    #     """Tool handler. Returns a JSON string, always."""
    #     try:
    #         return json.dumps({"result": _run(args, **kwargs)})
    #     except Exception as exc:
    #         return json.dumps({"error": f"{type(exc).__name__}: {exc}"})
    #
    # ctx.register_tool(
    #     name="{{tool_name}}",
    #     toolset="{{skill_name_underscored}}",
    #     schema={
    #         "type": "object",
    #         "properties": {"input": {"type": "string", "description": "input"}},
    #         "additionalProperties": False,
    #     },
    #     handler=_tool,
    #     description="{{tool description}}",
    #     emoji="🔧",
    # )
